import Head from "next/head";
import Carousel from "../components/Carousel";
import Products from "../components/Products";

export default function Home() {
	return (
		<div className="mt-16">
			<Head>
				<title>Home | Flipkart</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" />
			</Head>
			<main>
				<Carousel />
				<Products />
			</main>
		</div>
	);
}
