import Head from "next/head";
import { useSelector } from "react-redux";
import Carousel from "../components/Carousel";
import LoginModal from "../components/LoginModal";
import Products from "../components/Products";
import { selectLoginModal } from "../redux/slices/utilsSlice";

export default function Home({ products }) {
	const isLoginModalOpen = useSelector(selectLoginModal);
	return (
		<div className="mt-16">
			{isLoginModalOpen && <LoginModal />}
			<Head>
				<title>Home | Flipkart</title>
				<meta name="description" content="Generated by create next app" />
				<link
					rel="icon"
					href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico"
				/>
			</Head>
			<main>
				<Carousel />
				<Products products={products} />
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const products = await fetch("https://fakestoreapi.com/products").then((res) => res.json()).catch(() => []);
	return {
		props: {
			products: products,
		},
	};
}
